#:schema node_modules/wrangler/config-schema.json

name = "g-nettrack-uploads-api"
main = "src/index.ts"
compatibility_date = "2025-01-09"

[observability]
enabled = true

[placement]
mode = "smart"

[[r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "g-nettrack-logs"
